app <- ShinyDriver$new("../../")
app$snapshotInit("module-2-inputs")

app$snapshot()
app$setInputs(method = c("migspcr", "expert", "cc"))
app$setInputs(method = c("migspcr", "cc"))
app$setInputs(outcome = c("estimate", "ubar", "b", "t", "fmi", "df"))
app$setInputs(outcome = c("estimate", "ubar", "b", "t", "df"))
app$setInputs(term = c("Occupation", "Nativist", "Leader", "Issue", "Political_interest", "Political_action", "Married", "Urb", "Attendance", "Denom"))
app$setInputs(term = c("Nativist", "Leader", "Issue", "Political_interest", "Political_action", "Married", "Urb", "Attendance", "Denom"))
